// Code generated by trpc-go/trpc-cmdline v1.0.7. DO NOT EDIT.
// source: middle_proto.proto

package middle_trpc

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AccService defines service.
type AccService interface {
	OpenCheck(ctx context.Context, req *Request) (*Reply, error) // @alias=/Acc/OpenCheck
}

func AccService_OpenCheck_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &Request{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AccService).OpenCheck(ctx, reqbody.(*Request))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AccServer_ServiceDesc descriptor for server.RegisterService.
var AccServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.app.server.Acc",
	HandlerType: ((*AccService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.app.server.Acc/OpenCheck",
			Func: AccService_OpenCheck_Handler,
		},
	},
}

// RegisterAccService registers service.
func RegisterAccService(s server.Service, svr AccService) {
	if err := s.Register(&AccServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Acc register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAcc struct{}

func (s *UnimplementedAcc) OpenCheck(ctx context.Context, req *Request) (*Reply, error) {
	return nil, errors.New("rpc OpenCheck of service Acc is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AccClientProxy defines service client proxy
type AccClientProxy interface {
	OpenCheck(ctx context.Context, req *Request, opts ...client.Option) (rsp *Reply, err error) // @alias=/Acc/OpenCheck
}

type AccClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAccClientProxy = func(opts ...client.Option) AccClientProxy {
	return &AccClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AccClientProxyImpl) OpenCheck(ctx context.Context, req *Request, opts ...client.Option) (*Reply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.app.server.Acc/OpenCheck")
	msg.WithCalleeServiceName(AccServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("app")
	msg.WithCalleeServer("server")
	msg.WithCalleeService("Acc")
	msg.WithCalleeMethod("OpenCheck")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &Reply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
